<template>
	<div class="container grid min-h-fit grid-cols-12 gap-0 py-4 lg:gap-4">
		<div class="col-span-6 lg:col-span-3">
			<SidebarList>
				<li>
					<SidebarItem
						to="/dashboard/profile"
						:name="$t('common.menu.profile')"
						icon-name="user-circle"
						enableLeftSideBorder
					/>
				</li>
				<li>
					<SidebarItem
						to="/dashboard/subscription"
						:name="$t('common.menu.subscription')"
						icon-name="receipt-text"
						enableLeftSideBorder
					/>
				</li>
				<li>
					<SidebarItem
						to="/dashboard/order"
						:name="$t('common.menu.order')"
						icon-name="truck"
						enableLeftSideBorder
					/>
				</li>
				<li>
					<SidebarItem
						to="/dashboard/billing"
						:name="$t('common.menu.billing')"
						icon-name="dollar-circle"
						enableLeftSideBorder
					/>
				</li>
				<li>
					<SidebarItem
						to="/dashboard/relocate"
						:name="$t('common.menu.relocate')"
						icon-name="home-activity"
						enableLeftSideBorder
					/>
				</li>
				<li>
					<SidebarItem
						to="/dashboard/term-and-condition"
						:name="$t('common.menu.t&c_acceptance')"
						icon-name="badge-check"
						enableLeftSideBorder
					/>
				</li>
				<li>
					<SidebarItem
						to="/dashboard/mobile-bundle"
						:name="$t('common.menu.mobile_bundle')"
						icon-name="mobile"
						enableLeftSideBorder
					/>
				</li>
			</SidebarList>
		</div>
		<div class="col-span-6 min-h-[500px] p-10 pl-0 lg:col-span-9">
			<slot />
		</div>
	</div>
</template>
